#configuracion de acceso a BD
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
        ddl-auto: update 
 #estrategia de generacion de base de datos
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/BPZdbAPI
    username: postgres
    password: postgresql
    
    
server:
  port: 8090 

